### ISSUE TITLE
Important Question

### ISSUE THREAD

**Issue by jay-khatri** [tamuhack-org/moo#1]
But, what does the fox say?

**Comment by SaltyQuetzals** [comment]
@jay-khatri have you figured this out?

**Comment by jay-khatri** [comment]
@gracekfan this is an important issue, be respectful! @SaltyQuetzals still working on it, any ideas?

**Comment by SaltyQuetzals** [comment]
We have our best people working around the clock, no clue.

**Comment by jay-khatri** [comment]
Resolving this issue because we know it says: “Wa-pa-pa-pa-pa-pa-pow!
Wa-pa-pa-pa-pa-pa-pow!
Wa-pa-pa-pa-pa-pa-pow!”
