### ISSUE TITLE
Add TAMUhack 2019 to Past Iterations section

### ISSUE THREAD

**Issue by suvedhs** [tamuhack-org/moo#111]
TAMUhack 2019
Our 5th anniversary of TAMUhack :)

HowdyHack 2019
Our fall hackathon nearly triples in size!

**Comment by gracekfan** [comment]
nearly triples wat

**Comment by suvedhs** [comment]
60 ppl demoing to like 150+ ppl demoing

**Comment by gracekfan** [comment]
Add github icon to footer
fix footer alignment
get rid of collaborate
change tamuhack 2019 button to "coming soon"

**Comment by jonathan-innis** [comment]
Should I include the other information to past iterations?
