### ISSUE TITLE
Misaligned first & second bullets on timeline

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#131]
<img width="598" alt="Screen Shot 2019-11-08 at 4 45 28 PM" src="https://user-images.githubusercontent.com/33182506/68515611-3a2a3680-0247-11ea-8569-d13a96b57897.png">

**Comment by gracekfan** [comment]
<img width="704" alt="Screen Shot 2019-11-08 at 4 46 30 PM" src="https://user-images.githubusercontent.com/33182506/68515647-55954180-0247-11ea-847d-ff01a8684127.png">

**Comment by eightants** [comment]
Fixed with #127
