### ISSUE TITLE
Add new sponsors

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#135]
Statefarm (add after bp) & baker hughes (after exxon)

make apply button width 100% on mobile and a little bit wider on desktop

**Comment by sophialee0416** [comment]
Also GCP (after baker hughes)

**Comment by sophialee0416** [comment]
New sponsors:
GCP (after Baker Hughes), Pathrise (after GCP), SEC (after Pathrise), Voiceflow (after Contrary)
Partners:
Piada (after GoGo)

**Comment by eightants** [comment]
#136
