### ISSUE TITLE
Live site — registration closed

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#141]
Remove "apply button" -> change become a mentor & volunteer links to two buttons that say volunteer + mentor (volunteer -> solid black button/white text, mentor -> outline black + black text)

Change toast to from tamuhack 2020 registration is open -> view tamuhack 2020 website (make sure to change on workshop page too)

Change open registration content "Registration is open until Dec 20th. Apply now!" to -> "Apply to become a volunteer or a mentor!"

**Comment by SaltyQuetzals** [comment]
This can be merged early, just need @eightants to deploy on Dec. 20

**Comment by gracekfan** [comment]
we need a redeploy now rip bc we made changes last week but i forgot

**Comment by SaltyQuetzals** [comment]
@eightants

**Comment by eightants** [comment]
Redeployed
