### ISSUE TITLE
Style fixes on the TH21 websites

### ISSUE THREAD

**Issue by eightants** [tamuhack-org/moo#204]
![image](https://user-images.githubusercontent.com/29858539/102952707-5c0b6a80-4495-11eb-9d36-88a94e2e2984.png)
Notable fixes:
- Add right margin on the first section. Should be equal to left margin on the 2nd section. 
- Reduce navbar height a bit
- Margin between buttons
- On hover, sponsor logos should have cursor:pointer

**Comment by eightants** [comment]
@cameronbrill

**Comment by cameronbrill** [comment]
I think we need to crop the svg to move that content box over to the left, unless @eightants or @OneWebDev knows something I don't, in which case can you just make that change and push to the open PR #205

**Comment by eightants** [comment]
Just change the width of the svg?
