### ISSUE TITLE
Update "Past Iterations" timeline to include TAMUhack 2021.

### ISSUE THREAD

**Issue by OneWebDev** [tamuhack-org/moo#224]
## This issue will achieve the following:
* Adding a TAMUhack 2021 page to the timeline under "Past Iterations."
* Updating the TAMUhack 2021 page to have the appropriate name, logo, and description. See below.
* Changing the titles of current members of the team. See below.
* Adding the new members of the team to the TAMUhack 2021 page. See below.

## Helpful hints to make this issue easier:
* Much of the information between "HowdyHack 2020" is repeated on the new "TAMUhack 2021" page. It will help to copy over most of the member information.
	* https://github.com/tamuhack-org/moo/blob/d8804e695c81b06e82f2be8cd0dd9c3ec6ecdfe1/index.html#L864
* The only code modified in the index.html file for this PR should be the contents in hackathons array, found here:
	* https://github.com/tamuhack-org/moo/blob/d8804e695c81b06e82f2be8cd0dd9c3ec6ecdfe1/index.html#L419
* Add assets into the "static/assets/headshots/compressed" folder.
* If not provided a GitHub and/or LinkedIn, do not include the keys.
* Hackathon logos are added here:
	* https://github.com/tamuhack-org/moo/blob/f99f693b8f85273d435c7cec48f48b241c3efc3d/static/styles/horizontal-timeline.css#L1

## Text:
* name: "TAMUhack 2021"
* description: "Continuing our promise of a fun-filled hackathon, virtual style."
* logo: th21
	* actual logo found here: https://tamuhack.com/static/th-2021/img/logo.svg
* directors (from contact sheet)

**Comment by dylantheriot** [comment]
Additionally, put the new hackathon logo inside the [horizontal timeline assets folder](https://github.com/tamuhack-org/moo/tree/master/static/assets/horizontal-timeline)

**Comment by OneWebDev** [comment]
👍
