### ISSUE TITLE
Animation spacing — Mobile

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#43]
- [x] Increase size of plane
- [x] Move blimp lower
- [x] Move tamuhack lower (move everything under tamuhack lower too)
- [x] Make sun rotate slower

**Comment by jonathan-innis** [comment]
Still can't figure out what is causing the thing that Suvedh is seeing with the bar

**Comment by gracekfan** [comment]
> Still can't figure out what is causing the thing that Suvedh is seeing with the bar

@eightants had a solution in slack
