### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#45]
<img width="471" alt="Screen Shot 2019-06-17 at 6 04 57 PM" src="https://user-images.githubusercontent.com/33182506/59642405-7939dd00-912a-11e9-9f97-169b6090d767.png">

- [x] Fix weird occurrence on mobile with the timeline
- [x] Make footer less weird on mobile

On tamuhack.com/hh, when you hover over tamuhack in the nav, there's this weird black dash that appears
- [x] Fix that ^

<img width="210" alt="Screen Shot 2019-06-17 at 6 07 11 PM" src="https://user-images.githubusercontent.com/33182506/59642493-cae26780-912a-11e9-958e-57de0c6e54f6.png">

- [x] Fix the pink bar thing that Suvedh was talking about @eightants

**Comment by eightants** [comment]
Most of these should be addressed by #46

**Comment by jonathan-innis** [comment]
Closing with PR #47
