### ISSUE TITLE
Moar UI fixes

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#49]
WHAT WE DO
- [x] p class="lead emphasize" change font-weight to 500
- [x] p class="lead" & p class="custom-p-text" (just all p in your best judgment) change font-size to 16px, line-height: 30px; 
- [ ] Redirect Visit TAMUhack 2019 to last year's website (ask @AmanGotchu about it)

PAST ITERATIONS
- [x] Make timeline bar thinner (width: 12px)
- [x] Make timeline markers smaller (max/min width/height: 42px) (also have to change margins so the markers align with the bar)
- [ ] Add drop shadow to triangle part (make it consistent with the rectangle part)
 

ON MOBILE
- [x] Reduce spacing between the Visit HowdyHack 2019 button & the th img (same for th button and workshop img)
- [x] Fix display: block for navs (see image below)

<img width="477" alt="Screen Shot 2019-06-19 at 10 14 29 PM" src="https://user-images.githubusercontent.com/33182506/59815891-a8457f80-92df-11e9-814c-33eec940afef.png">

**Comment by jonathan-innis** [comment]
Font weight for lead emphasize already is 500...do you need it higher?

**Comment by jonathan-innis** [comment]
Are you referring to all the text...not just the span?
