### ISSUE TITLE
Add links to previous TAMUhack/HH websites to past iterations cards

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#57]

**Comment by gracekfan** [comment]
Fix HH 2018 font spacing/padding on mobile

**Comment by jonathan-innis** [comment]
How do we want to add this linking? Do we want it to be the entire card is clickable or part of the card is the link?

**Comment by gracekfan** [comment]
Entire card clickable, maybe hover state

**Comment by jay-khatri** [comment]
you're a hover state.

**Comment by jonathan-innis** [comment]
oof

**Comment by jonathan-innis** [comment]
Partially addressed by #86

**Comment by SaltyQuetzals** [comment]
@jonathan-innis Is this issue closeable? I can't click on the links on the page to go to the other sites.

**Comment by jonathan-innis** [comment]
Just added a commit that should fix that...forgot about mobile
