### ISSUE TITLE
Fix eventbrite Auth

### ISSUE THREAD

**Issue by jay-khatri** [tamuhack-org/moo#69]
Something funky is happening when we hit the Eventbrite API. 
You can see the error on this line: https://github.com/tamuhack-org/moo/blob/fc255a2ccdc696e8d01c25da0851c3559d47a68d/src/routes/workshop.ts#L10

**Comment by eightants** [comment]
Is this still an issue?

**Comment by jay-khatri** [comment]
nope, closing. cc @eightants @gracekfan
