### ISSUE TITLE
Fix past iteration cards on mobile

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/moo#72]
Add padding between dots and card
Make top padding equal to bottom padding

<img width="479" alt="Screen Shot 2019-07-28 at 3 43 06 PM" src="https://user-images.githubusercontent.com/33182506/62012645-7df0a880-b14e-11e9-9100-b4035cdf75d5.png">

**Comment by jonathan-innis** [comment]
Closed by #75
